#!/bin/bash

if [ ! -f "${HOME}/Desktop/libreoffice-writer.desktop" ]; then
  cp /usr/share/applications/libreoffice-*.desktop "${HOME}/Desktop/"
  rm -f "${HOME}/Desktop/libreoffice-xsltfilter.desktop"
fi

touch "${HOME}/.config/panel-reload"
